name: Test github actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install korgorusz/.[dev]
      - name: Run tests with pytest
        run: pytest korgorusz
      - name: Type checking
        run: mypy korgorusz
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: korgorusz
          use-mypy: false
          extra-pylint-options: "-d R0903 --good-names=l2,x,y,i"
